export const rows = [
  {
    id: 1,
    lastName: 'Snow',
    entryDate: 'July 17, 2021',
    firstName: 'Jon',
    category: 'HCP',
    email: 'sule@gmail.com',
    time: '10:00AM',
    medical: 123445,
    amount: '₦ 10,000',
    bank: 'Kuda MFB',
    subject: 'Appreciation message to Heala  team',
    status: 'active',
    specialization: 'Dentistry',
    availableTime: '10:00AM - 3:30PM',
    planName: 'Plan 1',
    roleName: 'role 1',
    description: 'This is the decription regarding this particular plan',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    data: ['create', 'read', 'update', 'delete'],
    type: 'Nurse',
    account: 2018785545,
    drugs: 'Panadol',
    affliation: 'H-Medix',
  },
  {
    id: 2,
    lastName: 'Lannister',
    roleName: 'role 1',
    entryDate: 'July 17, 2021',
    firstName: 'Cersei',
    category: 'User',
    planName: 'Plan 1',
    amount: '₦ 10,000',
    medical: 123445,
    bank: 'Kuda MFB',
    status: 'active',
    subject: 'Appreciation message to Heala  team',
    email: 'sule@gmail.com',
    description: 'This is the decription regarding this particular plan',
    availableTime: '10:00AM - 3:30PM',
    time: '10:00AM',
    specialization: 'Dentistry',
    permission: [
      'permission 1',
      'permission 2',
      'permission3',
      'permission4',
      'permission5',
      'permission6',
    ],
    data: ['create', 'read', 'update', 'delete'],
    type: 'Nurse',
    account: 2018785545,
    drugs: 'Panadol',
    affliation: 'H-Medix',
  },
  {
    id: 3,
    lastName: 'Lannister',
    account: 2018785545,
    roleName: 'role 1',
    affliation: 'H-Medix',
    bank: 'Kuda MFB',
    entryDate: 'July 17, 2021',
    firstName: 'Jaime',
    planName: 'Plan 1',
    category: 'HCP',
    drugs: 'Panadol',
    amount: '₦ 10,000',
    status: 'inactive',
    medical: 123445,
    email: 'sule@gmail.com',
    availableTime: '10:00AM - 3:30PM',
    time: '10:00AM',
    subject: 'Appreciation message to Heala  team',
    specialization: 'Dentistry',
    description: 'This is the decription regarding this particular plan',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    data: ['create', 'read', 'update', 'delete'],
    type: 'Nurse',
  },
  {
    id: 4,
    lastName: 'Stark',
    entryDate: 'July 17, 2021',
    affliation: 'H-Medix',
    roleName: 'role 1',
    firstName: 'Arya',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    category: 'HCP',
    amount: '₦ 10,000',
    email: 'sule@gmail.com',
    time: '10:00AM',
    planName: 'Plan 1',
    bank: 'Kuda MFB',
    availableTime: '10:00AM - 3:30PM',
    drugs: 'Panadol',
    medical: 123445,
    type: 'Doctor',
    subject: 'Appreciation message to Heala  team',
    status: 'active',
    specialization: 'Dentistry',
    description: 'This is the decription regarding this particular plan',
    data: ['create', 'read', 'update', 'delete'],
    account: 2018785545,
  },
  {
    id: 5,
    lastName: 'Targaryen',
    entryDate: 'July 17, 2021',
    firstName: 'Daenerys',
    category: 'HSP',
    medical: 123445,
    status: 'active',
    bank: 'Kuda MFB',
    drugs: 'Panadol',
    affliation: 'H-Medix',
    amount: '₦ 10,000',
    roleName: 'role 1',
    account: 2018785545,
    planName: 'Plan 1',
    email: 'sule@gmail.com',
    subject: 'Appreciation message to Heala  team',
    time: '10:00AM',
    specialization: 'Dentistry',
    availableTime: '10:00AM - 3:30PM',
    description: 'This is the decription regarding this particular plan',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    data: ['create', 'read', 'update', 'delete'],
    type: 'Doctor',
  },
  {
    id: 6,
    lastName: 'Melisandre',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    entryDate: 'July 17, 2021',
    roleName: 'role 1',
    data: ['create', 'read', 'update', 'delete'],
    firstName: null,
    status: 'active',
    medical: 123445,
    drugs: 'Panadol',
    affliation: 'H-Medix',
    account: 2018785545,
    bank: 'Kuda MFB',
    subject: 'Appreciation message to Heala  team',
    category: 'User',
    amount: '₦ 10,000',
    email: 'sule@gmail.com',
    time: '10:00AM',
    planName: 'Plan 1',
    specialization: 'Dentistry',
    description: 'This is the decription regarding this particular plan',
    type: 'Nurse',
  },
  {
    id: 7,
    lastName: 'Clifford',
    entryDate: 'July 17, 2021',
    medical: 123445,
    firstName: 'Ferrara',
    roleName: 'role 1',
    drugs: 'Panadol',
    affliation: 'H-Medix',
    subject: 'Appreciation message to Heala  team',
    category: 'HCP',
    status: 'active',
    planName: 'Plan 1',
    amount: '₦ 10,000',
    bank: 'Kuda MFB',
    email: 'sule@gmail.com',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    data: ['create', 'read', 'update', 'delete'],
    time: '10:00AM',
    specialization: 'Dentistry',
    availableTime: '10:00AM - 3:30PM',
    description: 'This is the decription regarding this particular plan',
    type: 'Nurse',
    account: 2018785545,
  },
  {
    id: 9,
    lastName: 'Roxie',
    entryDate: 'July 17, 2021',
    roleName: 'role 1',
    drugs: 'Panadol',
    firstName: 'Harvey',
    category: 'HCP',
    data: ['create', 'read', 'update', 'delete'],
    medical: 123445,
    subject: 'Appreciation message to Heala  team',
    status: 'active',
    affliation: 'H-Medix',
    planName: 'Plan 1',
    bank: 'Kuda MFB',
    amount: '₦ 10,000',
    email: 'sule@gmail.com',
    time: '10:00AM',
    specialization: 'Dentistry',
    permission: ['permission 1', 'permission 2', 'permission4', 'permission3'],
    availableTime: '10:00AM - 3:30PM',
    description: 'This is the decription regarding this particular plan',
    type: 'Nurse',
    account: 2018785545,
  },
]
